name: Emby Auto Build

on:
  schedule:
    - cron: '0 3 * * *' # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests packaging

      - name: Get latest Emby tag
        id: get_tag
        run: |
          LATEST_TAG=$(python scripts/get_latest_emby_tag.py)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Check if tag already built
        id: check_tag
        run: |
          if docker manifest inspect rajiska/emby-n150-fixed:$LATEST_TAG > /dev/null 2>&1; then
            echo "Tag $LATEST_TAG already exists. Skipping build."
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo "skip_build=false" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: env.skip_build != 'true'
        run: |
          docker buildx build --push --build-arg EMBY_TAG=$LATEST_TAG -t rajiska/emby-n150-fixed:$LATEST_TAG .